const roomTasks={Woonkamer:[['Stof de salontafel af','Elke 3 dagen'],['Stofzuig het tapijt','Elke 3 dagen'],['Klop de kussens op','Elke 5 dagen'],['Geef de planten water','Elke 2 dagen'],['Maak de ramen schoon','Elke 7 dagen'],['Ruim rondslingerend spul op','Elke dag']],Keuken:[['Maak het aanrecht schoon','Elke dag'],['Ruim de tafel af','Elke dag'],['Controleer de vaatwasser','Elke dag'],['Maak de kookplaat schoon','Elke 3 dagen'],['Dweil de vloer','Elke 5 dagen']],Badkamer:[['Maak de wastafel schoon','Elke 2 dagen'],['Vervang de handdoeken','Elke 3 dagen'],['Maak de spiegel schoon','Elke 5 dagen'],['Maak bad en douche schoon','Elke 7 dagen']],Slaapkamer:[['Maak het bed op','Elke dag'],['Ruim het nachtkastje op','Elke 3 dagen'],['Leg kleding weg','Elke dag']],Hal:[['Ruim schoenen op','Elke dag'],['Hang jassen netjes','Elke dag'],['Maak de vloer vrij','Elke dag']],Wasruimte:[['Sorteer de was','Elke dag'],['Maak de machine leeg','Elke dag'],['Ruim de wasmand op','Elke dag']],Terras:[['Maak de tafel netjes','Elke 3 dagen'],['Leg de kussens goed','Elke dag'],['Controleer de planten','Elke 2 dagen']]};
const roomIcons={Woonkamer:'🛋️',Keuken:'🍲',Badkamer:'🛁',Slaapkamer:'🛏️',Hal:'🚪',Wasruimte:'🧺',Terras:'🌿'};const roomImgs={Woonkamer:'task-3.png',Keuken:'task-1.png',Badkamer:'task-4.png',Slaapkamer:'task-5.png',Hal:'task-6.png',Wasruimte:'task-2.png',Terras:'task-4.png'};
function localDay(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
let state=JSON.parse(localStorage.getItem('homey-v15')||localStorage.getItem('homey-v14')||localStorage.getItem('homey-v13')||localStorage.getItem('homey-v12')||localStorage.getItem('homey-v11')||localStorage.getItem('homey-v10')||localStorage.getItem('homey-v9')||localStorage.getItem('homey-v8')||'null')||{points:0,coins:0,day:localDay(),done:{},bonusAwarded:false};if(state.day!==localDay()){state.day=localDay();state.done={};state.bonusAwarded=false}let currentRoom='Woonkamer';const $=id=>document.getElementById(id);const toast=$('toast');
function save(){localStorage.setItem('homey-v15',JSON.stringify(state))}function count(){return Object.values(state.done||{}).filter(Boolean).length}function msg(t){toast.textContent=t;toast.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>toast.classList.remove('show'),1400)}
function renderHome(){const n=Math.min(15,count());const hp=$('homePoints'),hc=$('homeCoins'),hb=$('homeBalls'),hbonus=$('homeBonus'),track=$('homeBallTrack');if(hp)hp.textContent=state.points||0;if(hc)hc.textContent=state.coins||0;if(hb)hb.textContent=`${n}/15`;if(hbonus)hbonus.textContent=`${n}/15`;if(track)track.innerHTML=Array.from({length:15},(_,i)=>`<span class="home-ball ${i<n?'filled':''}"></span>`).join('');document.querySelectorAll('[data-home-room]').forEach(el=>{const r=el.dataset.homeRoom;const total=(roomTasks[r]||[]).length;el.textContent=`${roomDone(r)}/${total}`})}
function renderLive(){renderHome();const n=Math.min(15,count());document.querySelectorAll('[data-points]').forEach(x=>x.textContent=state.points||0);document.querySelectorAll('[data-coins]').forEach(x=>x.textContent=state.coins||0);document.querySelectorAll('[data-balls]').forEach(x=>x.textContent=n);document.querySelectorAll('.to-bonus').forEach(x=>x.textContent=Math.max(0,15-n));document.querySelectorAll('.balls-track').forEach(t=>t.innerHTML=Array.from({length:15},(_,i)=>`<span class="ball ${i<n?'filled':''}"></span>`).join(''))}
function roomDone(r){return (roomTasks[r]||[]).filter((_,i)=>state.done[r+'-'+i]).length}function traffic(done,total){let s='';for(let i=0;i<12;i++)s+=`<span class="traffic-seg ${i<3?'red':i<6?'orange':'green'}"></span>`;let left=total?Math.max(2,Math.min(98,done/total*100)):2;let ratio=total?done/total:0;let marker=ratio<0.25?'red':ratio<0.5?'orange':'green';return s+`<span class="traffic-marker ${marker}" style="left:${left}%"></span>`}
function renderOverview(){const order=['Woonkamer','Keuken','Badkamer','Slaapkamer','Wasruimte','Terras'];$('roomCards').innerHTML=order.map((r,idx)=>{const total=roomTasks[r].length,done=roomDone(r),locked=idx>=3;return `<button class="room-card ${locked?'locked':''}" data-open-room="${r}"><img src="${roomImgs[r]}"><span class="room-card-main"><strong>${r}</strong>${locked?`<small>🔒 Vrijspelen op een 5e levelmoment</small>`:`<small>${total} taken</small><span class="mini-traffic">${traffic(done,total)}</span>`}</span><span class="room-arrow">${locked?'🔒':'›'}</span></button>`}).join('');renderLive()}
function openOverview(){hideAll();$('overview').hidden=false;renderOverview()}
function openRoom(r){currentRoom=r;hideAll();$('roomScreen').hidden=false;$('roomTitle').textContent=r;$('roomIcon').textContent=roomIcons[r]||'🌿';$('tasks').innerHTML=(roomTasks[r]||[]).map((a,i)=>{const k=r+'-'+i,d=!!state.done[k];return `<button class="task ${d?'done':''}" data-task="${k}"><img src="task-${(i%6)+1}.png"><span class="task-copy"><strong>${a[0]}</strong><small>${a[1]}</small></span><span class="rewards"><span>🪙 1</span><span>⭐ 5</span></span><span class="check"></span></button>`}).join('');renderLive();renderRoomProgress()}
function renderRoomProgress(){const total=roomTasks[currentRoom].length,done=roomDone(currentRoom);$('taskProgressText').textContent=`${done} van ${total} taken klaar`;$('taskPct').textContent=`${Math.round(done/total*100)}%`;$('taskProgressBar').innerHTML=traffic(done,total)}
function hideAll(){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$('overview').hidden=true;$('roomScreen').hidden=true;$('placeholder').hidden=true}
function go(w){hideAll();if(w==='home')$('home').classList.add('active');else if(w==='shop')$('shop').classList.add('active');else{$('placeholder').hidden=false;$('placeholderTitle').textContent=w==='inventory'?'Inventaris':w==='levels'?'Levels':'Meer'}renderLive()}
document.querySelectorAll('[data-overview]').forEach(b=>b.onclick=openOverview);$('roomCards').onclick=e=>{const b=e.target.closest('[data-open-room]');if(!b||b.classList.contains('locked'))return;openRoom(b.dataset.openRoom)};$('roomBack').onclick=openOverview;$('tasks').onclick=e=>{const b=e.target.closest('[data-task]');if(!b)return;const k=b.dataset.task;if(state.done[k]){state.done[k]=false;state.points=Math.max(0,state.points-5);state.coins=Math.max(0,state.coins-1);if(state.bonusAwarded&&count()<15){state.points=Math.max(0,state.points-15);state.bonusAwarded=false}}else{state.done[k]=true;state.points=(state.points||0)+5;state.coins=(state.coins||0)+1;if(count()>=15&&!state.bonusAwarded){state.points+=15;state.bonusAwarded=true;msg('Dagbonus! +15 punten 🎁')}}save();openRoom(currentRoom)};document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));renderLive();save();
