const tasks=[['Woonkamer','Kussens netjes leggen','🛋️',3],['Keuken','Aanrecht opruimen','🍽️',3],['Badkamer','Wastafel schoonmaken','🫧',2],['Slaapkamer','Bed opmaken','🛏️',2],['Hal','Jassen en schoenen opruimen','🧺',2],['Kleine taak','5 minuten opruimen','✨',3]];
const items=[['Grote kamerplant','🪴',12],['Boho kussen','🛋️',15],['Mooie vaas','🏺',18],['Wanddecoratie','🪞',20],['Gezellig tapijt','🧶',25],['Lampje','🪔',30]];
let state=JSON.parse(localStorage.getItem('homey')||'{"coins":0,"done":[],"bought":[]}');
function save(){localStorage.setItem('homey',JSON.stringify(state))}
function toggle(i){if(state.done.includes(i)){state.done=state.done.filter(x=>x!==i);state.coins=Math.max(0,state.coins-tasks[i][3])}else{state.done.push(i);state.coins+=tasks[i][3]}save();render()}
function buy(i){if(state.coins>=items[i][2]&&!state.bought.includes(i)){state.coins-=items[i][2];state.bought.push(i);save();render()}}
function render(){let d=state.done.length,l=Math.floor(d/5)+1;document.querySelector('#coins').textContent=state.coins;document.querySelector('#done').textContent=d;document.querySelector('#today').textContent=d;document.querySelector('#level').textContent=l;document.querySelector('#levelBig').textContent=l;document.querySelector('#bar').style.width=(d%5)*20+'%';document.querySelector('#progressText').textContent=d%5===0?`Level ${l} bereikt! 🎉`:`Nog ${5-d%5} bolletjes tot je volgende vrijspeling.`;document.querySelector('#nextUnlock').textContent='Level '+(Math.floor(d/5)+1);
document.querySelector('#tasks').innerHTML=tasks.map((t,i)=>`<div class="task ${state.done.includes(i)?'done':''}" onclick="toggle(${i})"><div class="ball">${t[2]}</div><div class="tasktext"><b>${t[0]}</b><small>${t[1]} · ${t[3]} bolletjes</small></div><b>${state.done.includes(i)?'✓':'○'}</b></div>`).join('');
document.querySelector('#shopitems').innerHTML=items.map((x,i)=>`<div class="item"><div class="pic">${x[1]}</div><b>${x[0]}</b><span class="price">🪙 ${x[2]}</span><button class="buy" ${state.bought.includes(i)||state.coins<x[2]?'disabled':''} onclick="buy(${i})">${state.bought.includes(i)?'Vrijgespeeld ✓':'Kopen'}</button></div>`).join('')}
function show(id,btn){document.querySelectorAll('main').forEach(x=>x.classList.add('hidden'));document.querySelector('#'+id).classList.remove('hidden');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));btn.classList.add('active')}
render()